### ISSUE TITLE
"fixklecks" necessary?

### ISSUE THREAD

**Issue by bitbof** [satopian/Petit_Note#8]
Hi,
I noticed you added some things to fix Klecks in https://github.com/satopian/Petit_Note/blob/master/petitnote/template/basic/paint_klecks.html

```html
<style>
body {
letter-spacing: initial;
word-break:initial;
}
li{margin:inherit;}
:not(input){
-moz-user-select: none;
-webkit-user-select: none;
-ms-user-select: none;
user-select: none;
}
</style>

<script>
	function fixklecks() {
		document.addEventListener('dblclick', function(e){ e.preventDefault()}, { passive: false });
	}
	window.addEventListener('DOMContentLoaded',fixklecks,false);
</script>
```

Are there issues in Klecks that show up without this? If so I can fix it in Klecks itself.

**Comment by satopian** [comment]
Hello.
This is based on the Javascript I added for the problem that chickenpaint doesn't work properly on the iPad, and I also used it in Klecks.
I don't have an iPad.
Therefore, I have not confirmed that the problem will occur.
This will be Javascript added for prevention.
Expected problem. Double tap zoom keeps the iPad magnified.
Press and hold the Apple Pencil to keep the screen selected.
If that can be avoided in Klecks itself, use it.
However, I'm not sure if there really is a problem with Klecks.
Since there is no iPad, the reproduction test relies on other users.

In tests by iPad users, I have received reports that it works fine in the Javascript environment I added.
If you, the creator of Klecks, decide that you can add the same functionality as the Javascript I added, please do so.

The English nuances may not be translated well.
please forgive me.

**Comment by bitbof** [comment]
Thanks for the detailed info! Klecks already takes measures to prevent these issues. I've verified by testing on my iPad and through feedback by users. Feel free to keep it in, I just wanted to make sure there isn't a bug that I'm unaware of.

**Comment by satopian** [comment]
[Help - Kleki](https://kleki.com/help/)

>iPad is stuck zoomed in
Due to a bug in iPadOS 13, you can end up stuck zoomed in after double-tapping.
How to fix it:
>- Tap on AA in the address bar
>- Tap the left A once, then the right once
>- Rotate your iPad 90° and wait for the orientation to change
>- Rotate your iPad back into the original position and wait for the orientation to change

>Now it should be back to normal.

it's fixd?

**Comment by bitbof** [comment]
I can't reproduce it with current iPadOS (15.4) at least. There are measures to prevent zoom. There was just an issue with that version of iPadOS.

**Comment by satopian** [comment]
It was a problem only for iOS 13. I finally understood.
thank you.

**Comment by satopian** [comment]
I delete the "function fixklecks ()".
I put it in that state and check if there are any issues.
And if there is a issues, I report it to the Klecks repository.

**Comment by bitbof** [comment]
That sounds good. Many thanks!
